# User Interface

The website navigation is divided into 3 sections: The top Main menu, the navigation buttons and side information panels. In the main menu you will find links to the most relevant options to manage your team and your account. These links have their own sub-menu. The reason for this choice is obviously to avoid too heavy menu-structure.

The first page you will see after you login is called the “Office Page”. You can always come back to this Office page by clicking the "House icon" located in the top right hand corner of any page or by clicking the game's logo in the top left hand corner of any page. On this page you will find many useful information such as News of the Game (issued by ADMs or other staff members), last updated Blogs, Elections and Polls alerts and warnings about private messages, bids received, challenges, next match, etc ...

**User (This menu is displayed with your user name):** All information related to the manager (you) will be on this menu. Here you will find information about your board's confidence, national & international manager rankings, links to access blogs and several other options. You can also find the link to change your PManager preferences on this menu. You will also have access to Job center and manage your second and/or third team (we'll talk about this further).

**Team (This menu is displayed with your team name):** This is the menu where you can deal with all related information concerning your team. You will find info about economy, transfers, staff, training, renewing contracts and changing/updating structures (stadium and academy). This menu also contains links to prepare your future matches (through Match Day >> Next Match -- or by clicking the "Next Match" link on the Office page directly below your Team's bank balance). This is the page where you can define your tactics, setup your starting line-up (Starting Eleven) and give lectures that affect your player's morale. You will also find reports from your Assistant Manager (about your own squad) and your Scout (about your next opponent), but only if you have hired them.

**Competitions:** On this menu, you will find links related to everything involving your current league's division and series. You can view league standings, fixtures and also a lot of statistics (top goal scorers, most valuable players and other awards). You also have the possibility to search for other divisions and series for any country. You can find all related information to National Cup, Friendly, PM Cups and Instant Friendlies Matches. Basically, everything that is related to your next match, you will find it on this menu.

**Community:** Through this menu you are able to configure and access the game's forums. You can also learn more about PMDD applications on this menu (applications designed by other managers that help you play the game). You are also able to search for other users, teams and players under the Search option under this menu. Here you also can find the Clans page

**The World:** Through this menu you'll be able to access information regarding National Federations, National teams (U21 and Main National Team), International Club Competitions and Player of the year page. You will be able to view future and prior friendly matches, info about all National Federations, National call-ups, the World Cup, etc. If you are appointed as a country's U21 or National Team (NT) coach..then you will find all of the tools under this menu -- National Teams >> Manager Menu.

**Stats:** This menu is for PM Fans only. This is the menu where all stats are located. Such as, most valuable players, most popular managers, richest teams, etc.

**Shop:** This menu explains what PM Fan actually gives you as a paying member of the community. You can also find the location of our online store to buy products to show your support in real life (t-shirts, sweatshirts, etc). Under this menu you can also buy or renew your PM Fan subscription and buy PM Coins for second or third team.

**Help:** Under this menu you can find the Rules of the Game (which you are currently reading), search for a mentor, keep updated with development news and Blog, gain the Manager Certificate, use cheaters report and contact us via Ticket Support System, and much more.

**Navigation Buttons**
As mentioned at the beginning, in every page there are 4 navigation buttons (top-right). These will allow an immediate navigation through sections. Let's list them:

- Home Button > Allows you to return to the Home-Office page with a single click!

- Last Page Button > Allows you to return to the page you visited immediately prior to the current

- Logout button > It disconnects from

**Navigation Bar & Player-to-Player Chat:**
We’ll start with the Navigation Bar: It’s a bar that it’s available on every page of PM that contains several links to the most used/important web pages of the game. By default this bar is placed on the bottom of all pages, in a fixed position. PM Fan users can totally customize this bar, as follows:

- Position (horizontal or vertical, having the possibility to drag and drop it to a custom location)

- Use icons or text as links (for the horizontal bar)

- Colors

- Size of the Bar

- Add/Remove other links (including external links)


The navigation bar also contains the Chat icon (first icon). This is the link to the player-to-player chat that will hopefully bring together all PM players a little more! Here’s how it works:

- This a free feature for all users. PM Fan users can keep up to 6 conversations at the same while non PM Fan users can keep only 3

- You can set yourself as Online, Online only for friends (users on your bookmark) or Offline.

- To start a chat with other player just go to his page and click on the "Chat with this player" link. There is a link on the forums as well, if the player is online.

Some other things you should know:

- It’s obvious that you must follow the general behavior rules (manual, chapter 29) on this chat.

- Messages older than 24 hours will be deleted.

- You cannot write messages with more than 255 characters.

- Only the last 20 messages within the chat session will be displayed.

- You cannot chat with a player that is "offline" from the game. Neither a player that has his Chat status set to Offline or Online for Friends Only (when you are not on his bookmarks). In these cases, your message won’t be delivered.

- We have fully tested these features for Firefox, Internet Explorer 7 (& above), Opera & Chrome.
