
# First Steps

You can begin to play the game after you receive the automated email from PManager telling you that your new team has been assigned to you. After you login for the first time it would be wise to take a look at the Help forums so that you can ask questions and learn from more experienced managers. Read the sticky posts in your help forum and the sticky posts in the Global Help forum. We can assure you that you'll find some great tips and advice in those two forums!

It is important to read this manual in full at least once, and always come back here if you ever have any doubts. You should not spend any of your initial funds until you understand the game a little bit better. Your initial funds are very important. We suggest that you do not head straight for the transfer market right after you get your team as you might end up wasting a lot of money on worthless players. Remember, the help forums are there for you – the newbie!

Another important feature that will help you learn the game better is the Mentor area. A game mentor is an experienced user that has voluntarily offered to help newbies in their first steps once they join the game. By default, all users will start with an automatic mentor. You can find the mentor's page by going to Help \>\> Mentors. You can either keep your current mentor or find another mentor. Mentors are rated with stars. You can select a highly rated mentor if you want.

**Countries**

To the right of the Help Menu, you can find a drop down box with the names of all countries within PManager. Selecting any country will change the country you're navigating in; the menu and respective options are slightly changed. This is because you will gain access to info regarding that country. For example, if you change the country to Portugal then that menu will show the matches and statistics of Portugal instead of your own. When you are away from your country, you lose access to all options related to your team (like the matches menu, team, etc).

**Players Skills**

All of the players have 12 different visible skills, and a few hidden skills. As it would be expected, some skills are more important for certain positions than others. Here you can find a chart that relates skills with player positions. You should pay more attention to the main attributes when assessing a player's quality. For more info, check Section 7 of the help menu which is labeled "Players".

**Goalkeeper**

[Main Attributes]{.underline}: Handling, Crosses \
[Secondary Attributes]{.underline}: Reflexes, Agility

**Defender**

[Main Attributes]{.underline}: Tackling, Heading \
[Secondary Attributes]{.underline}: Passing, Positioning

**Midfielder**

[Main Attributes]{.underline}: Passing, Positioning\
[Secondary Attributes]{.underline}: Tackling, Technique

**Forward**

[Main Attributes]{.underline}: Finishing, Technique\
[Secondary Attributes]{.underline}: Heading, Positioning

[Physical Skills]{.underline}: Speed, Strength

**Trainings**

Training is one of the most important factors in this game. You should always be aware of your player's training evolution. Training sessions take place after your league, friendly and cup matches have been played. No training occurs after tournament, playoffs or international competitions. Training is divided into two sections: global training and individual training. Global training is the training that your whole squad follows. Individual training is the kind of training that players follow individually. For more information, visit Section 8, *Training System*, of this Help Manual.

**Buying players**

Transfers of players between clubs in PManager are made through auctions. The selling club sets an asking price, and all managers interested in the player submit a bid. No bids may be placed below the minimum asking price. No one will know who made a bid on the player, but all managers (both selling & bidding) will have access to the average value of the ten highest bids. If you are the bidding team, you must have a scout to see the average bid and the level of your scout will influence that average bid's total. When the deadline has been reached, the club that offered the highest bid wins the auction and the player is transferred to that team immediately. To buy players or to obtain more information about how to buy players, visit the transfer market located under Team \>\> Transfers \>\> Transfer List.

You can view players currently listed in your own country by selecting National under that same menu. To visit all other country’s transfer markets, you must select Filter. For a listing of all Free Players (players who have been capped by their U21 or National Teams) select Free Players.
