# Strategies

There are some initial strategies that you can use to approach the game. Please bare in mind that these may not be the only ways to approach the game. You will have to decide for yourself how you want to play the game. Use these tips wisely and at your own risk!

Discuss your thoughts with your Mentor and your community. The more advice you receive, the better you are in the end!

**Academy / Training**

This strategy consists of saving all of your funds in order to improve your youth academy. Don't buy any players, just keep saving money until you have a top class academy. Once you have the World Class academy you can start promoting players from it. You should also know that it's not guaranteed that all players you pull from a World Class academy will be top-class. You'll be required to have a lot of patience until you have a full squad of high potential players.

As you can see, this is a long term strategy and you'll have to waste your initial 3/4 seasons in order to start pulling some decent players from your academy. Be patient with all of the negative results you'll probably find along your path! Hopefully, after a few seasons you will have a team made up almost exclusively of young players. These players will be full of potential and that will help your team move up in the PM division system as these players grow!

Most managers that used this strategy and failed, lacked a very important quality: patience. Once you have the World Class academy you have reached the final step of this strategy. Having a WC academy will ensure that you'll have a decent team sooner or later. Don't get frustrated by the lack of high potential players coming out of your academy in case this happens to you during your first few seasons. You'll be rewarded sooner or later. Once you start pulling the right players you can then readjust your strategy! Keep training? Start using the market? It's really up to you! But just don't forget about this: you'll have to be really patient and forget short-term success once you choose this approach.

**Training + Transfer Market**

This is a combined strategy. You'll have to scout the market in order to find young, cheap players with significant potential in order to train them for a couple of seasons and then sell them at higher prices just to re-start the process with other players. This process is known as season-trading! You can then use the money you earn to improve your squad with experienced and established players, or even with better potential players in order to train them faster and earn money faster.

This strategy is used by most managers after they start. The reasons are simple: the level of knowledge needed to do this is not that high (all newbies start with a low knowledge level!) and you'll only need a couple of months to start seeing your team getting some really good results. Just make sure that you get to know the market a little bit before you start buying your players, and (for example) don’t waste all of your money on one player. Use your initial million wisely, and try to buy as many young and high potential players as you can. Avoid paying more than 100.000 to 150.000 for each player in the beginning! Let's use an example ... Let's imagine that you buy 10 players for 100.000 per player. You'll then spend one to two seasons training them. Now let's imagine that you sell them for 200.000 each (minimum) after they are well trained. You will have a profit of 1 Million in the process! That's easy money! And believe us; it's not easy to earn 1 Million in four months, especially if you are still brand new to the game.

**Trading**

This is the strategy that will potentially give you faster results for your team. It basically consists of buying and selling players in a short period of time in order to make a profit. You'll need to have a pretty good idea of how the transfer market works in order to buy and sell for a quick profit. You should know if prices are high, low or average. This strategy requires you to buy low and sell high in a matter of days. The downside of this strategy is that you'll have to pay high transfer taxes because you are buying and selling players quickly. Transfer taxes decrease the longer a player is at your club. Once again, you should have the necessary knowledge to include these taxes in the selling price of these players. Your team will always have a low level of team-integration because these players will not remain at your club for a long period of time (team integration is explained further down in this Manual). Usually, the community does not consider this strategy very ethical. However, it is definitely not illegal. So, feel free to follow this strategy if you wish.